const defaultPadding = 5.0;
var mobileLoginBackGround = "assets/images/mobileLoginBackgroundImage.png";
var loginPageBackgroundImage = "assets/images/loginBackgroundImage.png";
var userImage = "assets/images/userimage.png";
var LoginID = "LoginID";
var LoginToken = "token";
var LoginEmail = "email";
var LoginRole = "role";
var placeHolderImage =
    "https://play-lh.googleusercontent.com/33VZ5V5cOf0td4-tMvaFmtFErja4nURmwhQG5_UvoPQRTQDPBhrwNASAm6rvmbm6EL8=w480-h960-rw";
var Information = "Information";
var Acknowledgment = "Acknowledgment";
var Response = "Response";
var messageTypeText = "Text";
var messageTypeImage = "Image";
var messageTypeAudio = "Audio";
var messageTypeVideo = "Video";
var Driver = "Driver";
var User = "User";
